### ISSUE TITLE
multiple proxies

### ISSUE THREAD

**Issue by drnic** [govau/instant-https-boshrelease#12]
I'd like to support multiple proxies on a single VM. I cannot do this at the bosh manifest level - each instance group (a VM) can only reference a job template once. So it needs to be implemented within the `proxy` job template.

As an example `spec`, I'd like to add:

```yaml
  proxies:
    description: A list of multiple proxies. Each has the same properties as above. The default value will come from above properties.
    example:
    - hostname: mainapp.com
      backends: [some-backend:8000]
    - hostname: staging.mainapp.com
      backends: [another-backend:9000]
```

It looks like a Caddyfile can only support a single hostname -> backends. So multiple `proxies` would mean multiple Caddyfiles and I guess multiple `check process caddy_123` in `monit`.

Thoughts or preferences on an implementation?
